name: MegaLinter

on:
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  megalinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_ALL_CODEBASE: false

          APPLY_FIXES: all
          APPLY_FIXES_EVENT: pull_request

          SHOW_ELAPSED_TIME: true
          PRINT_ALL_FILES: false

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: megalinter-reports
          path: megalinter-reports/
